### ISSUE TITLE
KeyError: 'FPNRatioPredictor'

### ISSUE THREAD

**Issue by gdwu1427** [MingtaoFu/gliding_vertex#11]
Hey,Mingtao.When I run the following code：python train_net.py  
KeyError: 'FPNRatioPredictor'   Can help me solve this problem thanks！
2020-04-03 10:32:25,397 maskrcnn_benchmark INFO: Saving config into: exp_dota/do                       ta/config.yml
Traceback (most recent call last):
  File "train_net.py", line 203, in <module>
    main()
  File "train_net.py", line 196, in main
    model = train(cfg, args.local_rank, args.distributed)
  File "train_net.py", line 37, in train
    model = build_detection_model(cfg)
  File "/home/znzk/dnn/package/maskrcnn-benchmark/maskrcnn_benchmark/modeling/de                       tector/detectors.py", line 10, in build_detection_model
    return meta_arch(cfg)
  File "/home/znzk/dnn/package/maskrcnn-benchmark/maskrcnn_benchmark/modeling/de                       tector/generalized_rcnn.py", line 31, in __init__
    self.roi_heads = build_roi_heads(cfg, self.backbone.out_channels)
  File "/home/znzk/dnn/package/maskrcnn-benchmark/maskrcnn_benchmark/modeling/ro                       i_heads/roi_heads.py", line 66, in build_roi_heads
    roi_heads.append(("box", build_roi_box_head(cfg, in_channels)))
  File "/home/znzk/dnn/package/maskrcnn-benchmark/maskrcnn_benchmark/modeling/ro                       i_heads/box_head/box_head.py", line 71, in build_roi_box_head
    return ROIBoxHead(cfg, in_channels)
  File "/home/znzk/dnn/package/maskrcnn-benchmark/maskrcnn_benchmark/modeling/ro                       i_heads/box_head/box_head.py", line 20, in __init__
    cfg, self.feature_extractor.out_channels)
  File "/home/znzk/dnn/package/maskrcnn-benchmark/maskrcnn_benchmark/modeling/ro                       i_heads/box_head/roi_box_predictors.py", line 61, in make_roi_box_predictor
    func = registry.ROI_BOX_PREDICTOR[cfg.MODEL.ROI_BOX_HEAD.PREDICTOR]
KeyError: 'FPNRatioPredictor'

**Comment by MingtaoFu** [comment]
I guess that you have modified the project or you are using the original maskrcnn-benchmark instead of our project. 

As you can see in https://github.com/MingtaoFu/gliding_vertex/blob/master/maskrcnn_benchmark/modeling/roi_heads/box_head/roi_box_predictors.py, ```FPNRatioPredictor``` is indeed registered in line 62.

On the other hand, ```func = registry.ROI_BOX_PREDICTOR[cfg.MODEL.ROI_BOX_HEAD.PREDICTOR]``` in our project is in line 97, however, it is in line 61 in your posted message.
 
So plz ensure that you are indeed using our project.
