### ISSUE TITLE
KeyError: 'Non-existent config key: INPUT.RANDOM_ROTATE_ON'

### ISSUE THREAD

**Issue by aimuch** [MingtaoFu/gliding_vertex#14]
Hi，again
There is another error:

(gliding_vertex) root@53e442ca6e5c:~/gliding_vertex# python -m torch.distributed.launch --nproc_per_node=1 tools/train_net.py --config-file configs/glide/dota.yaml
Traceback (most recent call last):
  File "tools/train_net.py", line 203, in <module>
    main()
  File "tools/train_net.py", line 170, in main
    cfg.merge_from_file(args.config_file)
  File "/root/anaconda3/envs/gliding_vertex/lib/python3.6/site-packages/yacs/config.py", line 213, in merge_from_file
    self.merge_from_other_cfg(cfg)
  File "/root/anaconda3/envs/gliding_vertex/lib/python3.6/site-packages/yacs/config.py", line 217, in merge_from_other_cfg
    _merge_a_into_b(cfg_other, self, self, [])
  File "/root/anaconda3/envs/gliding_vertex/lib/python3.6/site-packages/yacs/config.py", line 460, in _merge_a_into_b
    _merge_a_into_b(v, b[k], root, key_list + [k])
  File "/root/anaconda3/envs/gliding_vertex/lib/python3.6/site-packages/yacs/config.py", line 473, in _merge_a_into_b
    raise KeyError("Non-existent config key: {}".format(full_key))
KeyError: 'Non-existent config key: INPUT.RANDOM_ROTATE_ON'
Traceback (most recent call last):
  File "/root/anaconda3/envs/gliding_vertex/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/root/anaconda3/envs/gliding_vertex/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/anaconda3/envs/gliding_vertex/lib/python3.6/site-packages/torch/distributed/launch.py", line 235, in <module>
    main()
  File "/root/anaconda3/envs/gliding_vertex/lib/python3.6/site-packages/torch/distributed/launch.py", line 231, in main
    cmd=process.args)
subprocess.CalledProcessError: Command '['/root/anaconda3/envs/gliding_vertex/bin/python', '-u', 'tools/train_net.py', '--local_rank=0', '--config-file', 'configs/glide/dota.yaml']' returned non-zero exit status 1.

**Comment by aimuch** [comment]
> Hi，again
> There is another error:
> 
> (gliding_vertex) root@53e442ca6e5c:~/gliding_vertex# python -m torch.distributed.launch --nproc_per_node=1 tools/train_net.py --config-file configs/glide/dota.yaml
> Traceback (most recent call last):
> File "tools/train_net.py", line 203, in
> main()
> File "tools/train_net.py", line 170, in main
> cfg.merge_from_file(args.config_file)
> File "/root/anaconda3/envs/gliding_vertex/lib/python3.6/site-packages/yacs/config.py", line 213, in merge_from_file
> self.merge_from_other_cfg(cfg)
> File "/root/anaconda3/envs/gliding_vertex/lib/python3.6/site-packages/yacs/config.py", line 217, in merge_from_other_cfg
> _merge_a_into_b(cfg_other, self, self, [])
> File "/root/anaconda3/envs/gliding_vertex/lib/python3.6/site-packages/yacs/config.py", line 460, in _merge_a_into_b
> _merge_a_into_b(v, b[k], root, key_list + [k])
> File "/root/anaconda3/envs/gliding_vertex/lib/python3.6/site-packages/yacs/config.py", line 473, in _merge_a_into_b
> raise KeyError("Non-existent config key: {}".format(full_key))
> KeyError: 'Non-existent config key: INPUT.RANDOM_ROTATE_ON'
> Traceback (most recent call last):
> File "/root/anaconda3/envs/gliding_vertex/lib/python3.6/runpy.py", line 193, in _run_module_as_main
> "**main**", mod_spec)
> File "/root/anaconda3/envs/gliding_vertex/lib/python3.6/runpy.py", line 85, in _run_code
> exec(code, run_globals)
> File "/root/anaconda3/envs/gliding_vertex/lib/python3.6/site-packages/torch/distributed/launch.py", line 235, in
> main()
> File "/root/anaconda3/envs/gliding_vertex/lib/python3.6/site-packages/torch/distributed/launch.py", line 231, in main
> cmd=process.args)
> subprocess.CalledProcessError: Command '['/root/anaconda3/envs/gliding_vertex/bin/python', '-u', 'tools/train_net.py', '--local_rank=0', '--config-file', 'configs/glide/dota.yaml']' returned non-zero exit status 1.

Initially determined that maskrcnn-benchmark using error. I using official package

**Comment by 2018loveyyq** [comment]
I have encountered the same problem as you. Have you solved your problem？
