### ISSUE TITLE
可视化结果查看

### ISSUE THREAD

**Issue by Calen-J** [MingtaoFu/gliding_vertex#16]
请问inference.py如何使用，我一直报错
(256,)
2020-04-14 18:48:01,906 maskrcnn_benchmark.utils.model_serialization INFO: rpn.head.conv.weight                                  loaded from rpn.head.conv.weight                                  of shape (256, 256, 3, 3)
torch.Size([3, 800, 1123])
Traceback (most recent call last):
  File "tools/inference.py", line 233, in <module>
    main()
  File "tools/inference.py", line 186, in main
    rboxes = prediction.get_field( "rboxes" ).cpu()
  File "/home2/Jc/gliding_vertex-master/maskrcnn_benchmark/structures/bounding_box.py", line 43, in get_field
    return self.extra_fields[field]
KeyError: 'rboxes'

**Comment by Calen-J** [comment]
train和test都是用我自己的数据，没有问题，只有推断产生了这类问题

**Comment by wzz513878041** [comment]
你好，我也遇到了这个问题，请问你的问题解决了吗？

**Comment by wangyanfu123** [comment]
我也遇到了同样的问题，请问你怎么解决的

**Comment by wangyanfu123** [comment]
> 你好，我也遇到了这个问题，请问你的问题解决了吗？

**Comment by 1172066589** [comment]
您好，请问现在有方法解决吗，谢谢了

**Comment by xiyufeng2** [comment]
你好！可视化结果infrence.py中，只有框，没有类别信息。代码里输出结果prediction中，也只有4个参数：hbox、rbbox、ratio、scores。请问如何生成并显示类别信息
