### ISSUE TITLE
How to get the file "data/R-101.pkl"?

### ISSUE THREAD

**Issue by ZhWL123456** [MingtaoFu/gliding_vertex#29]
Traceback (most recent call last):
  File "tools/train_net.py", line 209, in <module>
    main()
  File "tools/train_net.py", line 202, in main
    model = train(cfg, args.local_rank, args.distributed)
  File "tools/train_net.py", line 72, in train
    extra_checkpoint_data = checkpointer.load(cfg.MODEL.WEIGHT)
  File "/home/zwl/Network/gliding_vertex/maskrcnn_benchmark/utils/checkpoint.py", line 61, in load
    checkpoint = self._load_file(f)
  File "/home/zwl/Network/gliding_vertex/maskrcnn_benchmark/utils/checkpoint.py", line 134, in _load_file
    return load_c2_format(self.cfg, f)
  File "/home/zwl/Network/gliding_vertex/maskrcnn_benchmark/utils/c2_model_loading.py", line 208, in load_c2_format
    return C2_FORMAT_LOADER[cfg.MODEL.BACKBONE.CONV_BODY](cfg, f)
  File "/home/zwl/Network/gliding_vertex/maskrcnn_benchmark/utils/c2_model_loading.py", line 194, in load_resnet_c2_format
    state_dict = _load_c2_pickled_weights(f)
  File "/home/zwl/Network/gliding_vertex/maskrcnn_benchmark/utils/c2_model_loading.py", line 134, in _load_c2_pickled_weights
    with open(file_path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/R-101.pkl'
Traceback (most recent call last):
  File "tools/train_net.py", line 209, in <module>
    main()
  File "tools/train_net.py", line 202, in main
    model = train(cfg, args.local_rank, args.distributed)
  File "tools/train_net.py", line 72, in train
    extra_checkpoint_data = checkpointer.load(cfg.MODEL.WEIGHT)
  File "/home/zwl/Network/gliding_vertex/maskrcnn_benchmark/utils/checkpoint.py", line 61, in load
    checkpoint = self._load_file(f)
  File "/home/zwl/Network/gliding_vertex/maskrcnn_benchmark/utils/checkpoint.py", line 134, in _load_file
    return load_c2_format(self.cfg, f)
  File "/home/zwl/Network/gliding_vertex/maskrcnn_benchmark/utils/c2_model_loading.py", line 208, in load_c2_format
    return C2_FORMAT_LOADER[cfg.MODEL.BACKBONE.CONV_BODY](cfg, f)
  File "/home/zwl/Network/gliding_vertex/maskrcnn_benchmark/utils/c2_model_loading.py", line 194, in load_resnet_c2_format
    state_dict = _load_c2_pickled_weights(f)
  File "/home/zwl/Network/gliding_vertex/maskrcnn_benchmark/utils/c2_model_loading.py", line 134, in _load_c2_pickled_weights
    with open(file_path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/R-101.pkl'

**Comment by mundanePeo** [comment]
I meet the same problem. Do you solved it?

**Comment by MingtaoFu** [comment]
https://dl.fbaipublicfiles.com/detectron/ImageNetPretrained/MSRA/R-101.pkl

**Comment by ZhWL123456** [comment]
> https://dl.fbaipublicfiles.com/detectron/ImageNetPretrained/MSRA/R-101.pkl

Thank u~

**Comment by ZhWL123456** [comment]
> I meet the same problem. Do you solved it?

The author has replied!
