### ISSUE TITLE
KeyError: 'rboxes'

### ISSUE THREAD

**Issue by wangyanfu123** [MingtaoFu/gliding_vertex#34]
请问inference.py如何使用，我一直报错
(256,)
2020-04-14 18:48:01,906 maskrcnn_benchmark.utils.model_serialization INFO: rpn.head.conv.weight loaded from rpn.head.conv.weight of shape (256, 256, 3, 3)
torch.Size([3, 800, 1123])
Traceback (most recent call last):
File "tools/inference.py", line 233, in
main()
File "tools/inference.py", line 186, in main
rboxes = prediction.get_field( "rboxes" ).cpu()
File "/home2/Jc/gliding_vertex-master/maskrcnn_benchmark/structures/bounding_box.py", line 43, in get_field
return self.extra_fields[field]
KeyError: 'rboxes'

**Comment by 1172066589** [comment]
您好，请问现在解决了吗
