### ISSUE TITLE
environment configuration problem

### ISSUE THREAD

**Issue by missFuture** [MingtaoFu/gliding_vertex#5]
Hi, Mingtao, I meet some environment problems under the process of using this repository.here are some steps I executed.

- First I follow the [instruction](https://github.com/facebookresearch/maskrcnn-benchmark/blob/73ed87954c971b4f6f38d9da442bcac51055353e/INSTALL.md) to prepare the environment.Except the last step `git clone https://github.com/facebookresearch/maskrcnn-benchmark.git`.

- Then I git clone your repository and execute `python setup.py build develop` under the gliding_vertex directory(REPO_ROOT). there is no mistake

- Finally, I execute `python setup.py build_ext --inplace` under the poly_nms directory and add mask_rcnn into $PYTHONPATH. 

- Then I try to train my dataset, there are some mistake as follows.

I have tried cudatookit9.2, pytorch1.5.0, pytorch1.2.0 for some days.but they didn't work.

I really want to know your environment configuration information.(Pytorch1.2.0 or pytorch-nightly1.2.0 dev20190704? or torch-nightly1.2.0). if it is pytorch-nightly1.2.0, where should I download it? I just pip install [torch_nightly-1.2.0.dev20190727%2Bcu92-cp36-cp36m-linux_x86_64.whl](https://download.pytorch.org/whl/nightly/cu92/torch_nightly.html), because conda can only install pytorch-nightly for 1.0.0 version, however,  it didn't work.

Could you give me some other advice about my installation process? I am a  fresh men, I am looking forward to recceive your anwser.

My environment information:
system:ubuntu16.04
GPU:4*TITANX
Cuda compilation tools, release 9.0, V9.0.176
cudatoolkit: 9.0
cudnn:6.0
pytorch-nightly 1.0.0.dev20190328 py3.6_cuda9.0.176_cudnn7.4.2_0
torchvision:0.3.0
pytorch 1.2.0
torch.cuda.is_available():True
trian command:python -m torch.distributed.launch --nproc_per_node=3 tools/train_net.py --config-file configs/glide/grasp_first.yaml

**Error information:**
  File "tools/train_net.py", line 15, in <module>
    from maskrcnn_benchmark.data import make_data_loader
  File "/home/lixulong/catkin_ws_grasp/src/gliding_vertix/gliding_vertex/maskrcnn_benchmark/data/__init__.py", line 2, in <module>
    from .build import make_data_loader
  File "/home/lixulong/catkin_ws_grasp/src/gliding_vertix/gliding_vertex/maskrcnn_benchmark/data/build.py", line 11, in <module>
    from . import datasets as D
  File "/home/lixulong/catkin_ws_grasp/src/gliding_vertix/gliding_vertex/maskrcnn_benchmark/data/datasets/__init__.py", line 2, in <module>
    from .coco import COCODataset
  File "/home/lixulong/catkin_ws_grasp/src/gliding_vertix/gliding_vertex/maskrcnn_benchmark/data/datasets/coco.py", line 3, in <module>
    import torchvision
  File "/home/lixulong/anaconda3/envs/mask/lib/python3.6/site-packages/torchvision/__init__.py", line 1, in <module>
    from torchvision import models
  File "/home/lixulong/anaconda3/envs/mask/lib/python3.6/site-packages/torchvision/models/__init__.py", line 11, in <module>
    from . import detection
  File "/home/lixulong/anaconda3/envs/mask/lib/python3.6/site-packages/torchvision/models/detection/__init__.py", line 1, in <module>
    from .faster_rcnn import *
  File "/home/lixulong/anaconda3/envs/mask/lib/python3.6/site-packages/torchvision/models/detection/faster_rcnn.py", line 7, in <module>
    from torchvision.ops import misc as misc_nn_ops
  File "/home/lixulong/anaconda3/envs/mask/lib/python3.6/site-packages/torchvision/ops/__init__.py", line 1, in <module>
    from .boxes import nms, box_iou
  File "/home/lixulong/anaconda3/envs/mask/lib/python3.6/site-packages/torchvision/ops/boxes.py", line 2, in <module>
    from torchvision import _C
ImportError: /home/lixulong/anaconda3/envs/mask/lib/python3.6/site-packages/torchvision/_C.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN3c1019ComplexCUDATensorIdEv
Traceback (most recent call last):
  File "tools/train_net.py", line 15, in <module>
    from maskrcnn_benchmark.data import make_data_loader
  File "/home/lixulong/catkin_ws_grasp/src/gliding_vertix/gliding_vertex/maskrcnn_benchmark/data/__init__.py", line 2, in <module>
    from .build import make_data_loader
  File "/home/lixulong/catkin_ws_grasp/src/gliding_vertix/gliding_vertex/maskrcnn_benchmark/data/build.py", line 11, in <module>
    from . import datasets as D
  File "/home/lixulong/catkin_ws_grasp/src/gliding_vertix/gliding_vertex/maskrcnn_benchmark/data/datasets/__init__.py", line 2, in <module>
    from .coco import COCODataset
  File "/home/lixulong/catkin_ws_grasp/src/gliding_vertix/gliding_vertex/maskrcnn_benchmark/data/datasets/coco.py", line 3, in <module>
    import torchvision
  File "/home/lixulong/anaconda3/envs/mask/lib/python3.6/site-packages/torchvision/__init__.py", line 1, in <module>
    from torchvision import models
  File "/home/lixulong/anaconda3/envs/mask/lib/python3.6/site-packages/torchvision/models/__init__.py", line 11, in <module>
    from . import detection
  File "/home/lixulong/anaconda3/envs/mask/lib/python3.6/site-packages/torchvision/models/detection/__init__.py", line 1, in <module>
    from .faster_rcnn import *
  File "/home/lixulong/anaconda3/envs/mask/lib/python3.6/site-packages/torchvision/models/detection/faster_rcnn.py", line 7, in <module>
    from torchvision.ops import misc as misc_nn_ops
  File "/home/lixulong/anaconda3/envs/mask/lib/python3.6/site-packages/torchvision/ops/__init__.py", line 1, in <module>
    from .boxes import nms, box_iou
  File "/home/lixulong/anaconda3/envs/mask/lib/python3.6/site-packages/torchvision/ops/boxes.py", line 2, in <module>
    from torchvision import _C
ImportError: /home/lixulong/anaconda3/envs/mask/lib/python3.6/site-packages/torchvision/_C.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN3c1019ComplexCUDATensorIdEv
Traceback (most recent call last):
  File "tools/train_net.py", line 15, in <module>
    from maskrcnn_benchmark.data import make_data_loader
  File "/home/lixulong/catkin_ws_grasp/src/gliding_vertix/gliding_vertex/maskrcnn_benchmark/data/__init__.py", line 2, in <module>
    from .build import make_data_loader
  File "/home/lixulong/catkin_ws_grasp/src/gliding_vertix/gliding_vertex/maskrcnn_benchmark/data/build.py", line 11, in <module>
    from . import datasets as D
  File "/home/lixulong/catkin_ws_grasp/src/gliding_vertix/gliding_vertex/maskrcnn_benchmark/data/datasets/__init__.py", line 2, in <module>
    from .coco import COCODataset
  File "/home/lixulong/catkin_ws_grasp/src/gliding_vertix/gliding_vertex/maskrcnn_benchmark/data/datasets/coco.py", line 3, in <module>
    import torchvision
  File "/home/lixulong/anaconda3/envs/mask/lib/python3.6/site-packages/torchvision/__init__.py", line 1, in <module>
    from torchvision import models
  File "/home/lixulong/anaconda3/envs/mask/lib/python3.6/site-packages/torchvision/models/__init__.py", line 11, in <module>
    from . import detection
  File "/home/lixulong/anaconda3/envs/mask/lib/python3.6/site-packages/torchvision/models/detection/__init__.py", line 1, in <module>
    from .faster_rcnn import *
  File "/home/lixulong/anaconda3/envs/mask/lib/python3.6/site-packages/torchvision/models/detection/faster_rcnn.py", line 7, in <module>
    from torchvision.ops import misc as misc_nn_ops
  File "/home/lixulong/anaconda3/envs/mask/lib/python3.6/site-packages/torchvision/ops/__init__.py", line 1, in <module>
    from .boxes import nms, box_iou
  File "/home/lixulong/anaconda3/envs/mask/lib/python3.6/site-packages/torchvision/ops/boxes.py", line 2, in <module>
    from torchvision import _C
ImportError: /home/lixulong/anaconda3/envs/mask/lib/python3.6/site-packages/torchvision/_C.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN3c1019ComplexCUDATensorIdEv
Traceback (most recent call last):
  File "/home/lixulong/anaconda3/envs/mask/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/lixulong/anaconda3/envs/mask/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/lixulong/anaconda3/envs/mask/lib/python3.6/site-packages/torch/distributed/launch.py", line 238, in <module>
    main()
  File "/home/lixulong/anaconda3/envs/mask/lib/python3.6/site-packages/torch/distributed/launch.py", line 234, in main
    cmd=process.args)
subprocess.CalledProcessError: Command '['/home/lixulong/anaconda3/envs/mask/bin/python', '-u', 'tools/train_net.py', '--local_rank=0', '--config-file', 'configs/glide/grasp_first.yaml']' returned non-zero exit status 1.

**Comment by MingtaoFu** [comment]
Pytorch-nightly1.2.0 dev20190704 should work.
Did you recompile the dependences after switching to a new version of PyTorch?

**Comment by missFuture** [comment]
thanks for your reply.
I have solved this problem by recompling all the project(mask-rcnn and gliding vertex).
**current environment information**
PyTorch version: 1.0.0.dev20190328
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.0.176
GPU models and configuration: 
GPU 0: TITAN X (Pascal)
GPU 1: TITAN X (Pascal)
GPU 2: TITAN X (Pascal)
GPU 3: TITAN X (Pascal)

Nvidia driver version: 390.116
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.5.1.10
/usr/lib/x86_64-linux-gnu/libcudnn.so.6.0.21
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
/usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudnn.so.5.1.5

Versions of relevant libraries:
[pip3] numpy==1.11.0
[conda] mkl                       2020.0                      166    defaults
[conda] pytorch                   1.1.0           py3.6_cuda9.0.176_cudnn7.5.1_0    pytorch
[conda] pytorch-nightly           1.0.0.dev20190328 py3.6_cuda9.0.176_cudnn7.4.2_0    pytorch
[conda] torchvision               0.2.2.post3               <pip>
[conda] torchvision               0.3.0           py36_cu9.0.176_1    pytorch
