### ISSUE TITLE
您好，我想要训练ICDAR2015数据，我用您给的方法变换数据集不太对

### ISSUE THREAD

**Issue by shenhongjuan** [MingtaoFu/gliding_vertex#7]

**Comment by MingtaoFu** [comment]
请提供具体的错误信息。

**Comment by shenhongjuan** [comment]
Traceback (most recent call last):
  File "pp.py", line 3, in <module>
    img_dic = collect_unaug_dataset(os.path.join("/home/dc2-user/shj/gliding_vertex-master/gliding_vertex-master/Challenge4/", "ch4_training_localization_transcription_gt/"))
  File "/home/dc2-user/shj/gliding_vertex-master/gliding_vertex-master/txt2json.py", line 143, in collect_unaug_dataset
    img_dic[key].append( txt[:-4] )
KeyError: '###\n'

**Comment by MingtaoFu** [comment]
您好，请阅读README，txt的格式为 ```x1 y1 x2 y2 x3 y3 x4 y4 cls diff```。这个问题应该是由于该数据集只有一个类，因此没有cls导致的。另外，这个脚本的diff是0/1的，而ICDAR的标注如果是diff则是###，也应该进行修改。

**Comment by shenhongjuan** [comment]
Traceback (most recent call last):
File "tools/train_net.py", line 15, in <module>
from maskrcnn_benchmark.data import make_data_loader
File "/home/dc2-user/code/gliding_vertex-master/maskrcnn_benchmark/data/__init__.py", line 2, in <module>
from .build import make_data_loader
File "/home/dc2-user/code/gliding_vertex-master/maskrcnn_benchmark/data/build.py", line 11, in <module>
from . import datasets as D
File "/home/dc2-user/code/gliding_vertex-master/maskrcnn_benchmark/data/datasets/__init__.py", line 2, in <module>
from .coco import COCODataset
File "/home/dc2-user/code/gliding_vertex-master/maskrcnn_benchmark/data/datasets/coco.py", line 3, in <module>
import torchvision
File "/home/dc2-user/ENTER/envs/mask/lib/python3.6/site-packages/torchvision/__init__.py", line 1, in <module>
from torchvision import models
File "/home/dc2-user/ENTER/envs/mask/lib/python3.6/site-packages/torchvision/models/__init__.py", line 11, in <module>
from . import detection
File "/home/dc2-user/ENTER/envs/mask/lib/python3.6/site-packages/torchvision/models/detection/__init__.py", line 1, in <module>
from .faster_rcnn import *
File "/home/dc2-user/ENTER/envs/mask/lib/python3.6/site-packages/torchvision/models/detection/faster_rcnn.py", line 7, in <module>
from torchvision.ops import misc as misc_nn_ops
File "/home/dc2-user/ENTER/envs/mask/lib/python3.6/site-packages/torchvision/ops/__init__.py", line 1, in <module>
from .boxes import nms, box_iou
File "/home/dc2-user/ENTER/envs/mask/lib/python3.6/site-packages/torchvision/ops/boxes.py", line 2, in <module>
from torchvision import _C
ImportError: /home/dc2-user/ENTER/envs/mask/lib/python3.6/site-packages/torchvision/_C.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN3c1019ComplexCUDATensorIdEv
Traceback (most recent call last):
File "/home/dc2-user/ENTER/envs/mask/lib/python3.6/runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "/home/dc2-user/ENTER/envs/mask/lib/python3.6/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/home/dc2-user/ENTER/envs/mask/lib/python3.6/site-packages/torch/distributed/launch.py", line 238, in <module>
main()
File "/home/dc2-user/ENTER/envs/mask/lib/python3.6/site-packages/torch/distributed/launch.py", line 234, in main
cmd=process.args)
subprocess.CalledProcessError: Command '['/home/dc2-user/ENTER/envs/mask/bin/python', '-u', 'tools/train_net.py', '--local_rank=0', '--config-file', 'configs/glide/common.yaml']' returned non-zero exit status 1.

您好，训练您的这个代码总是报这个错误，cuda10和cuda9 pytorch1.10, 1.2.0 ，pytorch-nightly1.0.0都试过了



在 2020-03-28 15:32:42，"Mingtao Fu" <notifications@github.com> 写道：

您好，请阅读README，txt的格式为 x1 y1 x2 y2 x3 y3 x4 y4 cls diff。这个问题应该是由于该数据集只有一个类，因此没有cls导致的。另外，这个脚本的diff是0/1的，而ICDAR的标注如果是diff则是###，也应该进行修改。
