### ISSUE TITLE
train

### ISSUE THREAD

**Issue by liwenjielongren** [MingtaoFu/gliding_vertex#8]
hi，when I run python -m torch.distributed.launch --nproc_per_node=3 tools/train_net.py --config-file configs/glide/dota.yaml .there is a error:

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************
Traceback (most recent call last):
  File "tools/train_net.py", line 17, in <module>
    from maskrcnn_benchmark.data import make_data_loader
  File "tools/../maskrcnn_benchmark/data/__init__.py", line 2, in <module>
    from .build import make_data_loader
  File "tools/../maskrcnn_benchmark/data/build.py", line 11, in <module>
    from . import datasets as D
  File "tools/../maskrcnn_benchmark/data/datasets/__init__.py", line 2, in <module>
    from .coco import COCODataset
  File "tools/../maskrcnn_benchmark/data/datasets/coco.py", line 6, in <module>
    from maskrcnn_benchmark.structures.segmentation_mask import SegmentationMask
  File "tools/../maskrcnn_benchmark/structures/segmentation_mask.py", line 5, in <module>
    from maskrcnn_benchmark.layers.misc import interpolate
  File "tools/../maskrcnn_benchmark/layers/__init__.py", line 10, in <module>
    from .nms import nms
  File "tools/../maskrcnn_benchmark/layers/nms.py", line 3, in <module>
    from maskrcnn_benchmark import _C
ImportError: cannot import name '_C'
Traceback (most recent call last):
  File "/Share/home/E19301170/anaconda3/envs/gliding_v/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Share/home/E19301170/anaconda3/envs/gliding_v/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Share/home/E19301170/anaconda3/envs/gliding_v/lib/python3.6/site-packages/torch/distributed/launch.py", line 246, in <module>
    main()
  File "/Share/home/E19301170/anaconda3/envs/gliding_v/lib/python3.6/site-packages/torch/distributed/launch.py", line 242, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/Share/home/E19301170/anaconda3/envs/gliding_v/bin/python', '-u', 'tools/train_net.py', '--local_rank=2', '--config-file', 'configs/glide/dota.yaml']' returned non-zero exit status 1.
(gliding_v) [E19301170@ln01 gliding_vertex_master]$ Traceback (most recent call last):
  File "tools/train_net.py", line 17, in <module>
    from maskrcnn_benchmark.data import make_data_loader
  File "tools/../maskrcnn_benchmark/data/__init__.py", line 2, in <module>
    from .build import make_data_loader
  File "tools/../maskrcnn_benchmark/data/build.py", line 11, in <module>
    from . import datasets as D
  File "tools/../maskrcnn_benchmark/data/datasets/__init__.py", line 2, in <module>
    from .coco import COCODataset
  File "tools/../maskrcnn_benchmark/data/datasets/coco.py", line 6, in <module>
    from maskrcnn_benchmark.structures.segmentation_mask import SegmentationMask
  File "tools/../maskrcnn_benchmark/structures/segmentation_mask.py", line 5, in <module>
    from maskrcnn_benchmark.layers.misc import interpolate
  File "tools/../maskrcnn_benchmark/layers/__init__.py", line 10, in <module>
    from .nms import nms
  File "tools/../maskrcnn_benchmark/layers/nms.py", line 3, in <module>
    from maskrcnn_benchmark import _C
ImportError: cannot import name '_C'
Traceback (most recent call last):
  File "tools/train_net.py", line 17, in <module>
    from maskrcnn_benchmark.data import make_data_loader
  File "tools/../maskrcnn_benchmark/data/__init__.py", line 2, in <module>
    from .build import make_data_loader
  File "tools/../maskrcnn_benchmark/data/build.py", line 11, in <module>
    from . import datasets as D
  File "tools/../maskrcnn_benchmark/data/datasets/__init__.py", line 2, in <module>
    from .coco import COCODataset
  File "tools/../maskrcnn_benchmark/data/datasets/coco.py", line 6, in <module>
    from maskrcnn_benchmark.structures.segmentation_mask import SegmentationMask
  File "tools/../maskrcnn_benchmark/structures/segmentation_mask.py", line 5, in <module>
    from maskrcnn_benchmark.layers.misc import interpolate
  File "tools/../maskrcnn_benchmark/layers/__init__.py", line 10, in <module>
    from .nms import nms
  File "tools/../maskrcnn_benchmark/layers/nms.py", line 3, in <module>
    from maskrcnn_benchmark import _C
ImportError: cannot import name '_C'

**Comment by tianhaoyue** [comment]
@liwenjielongren  请问您的问题解决了吗？烦请告知。

**Comment by liwenjielongren** [comment]
_C is not used to open the config files.The _C is from the file _C.cpython-36m-x86_64-linux-gnu.so in maskrcnn-benchmark which is produced by the lines "python setup.py build develop".

**Comment by tianhaoyue** [comment]
> _C is not used to open the config files.The _C is from the file _C.cpython-36m-x86_64-linux-gnu.so in maskrcnn-benchmark which is produced by the lines "python setup.py build develop".

Thanks very much!
